#!/bin/bash
# tty forwarder/relay over ssh
# serves an interactive shell/command on a remote host using ssh
# connnect to it from remote host
# example:
#   serve a shell on host to remote: rbs -r <remote> 
#   connect to host from remote: rbs
#
# Author: joknarf

usage() {
  printf '%s' 'usage: 
  server: rbs -r <remote> [-p <port>|-S <sock>] [-P <passfile|->] [-t ttyserver] [-T <ttysrvname>] [-R <remotename>] [-b <bind>] [-c config] [-C <command>] [-a] [-s]
  client: rbs [-p port|-S <sock>] [-T <ttysrname>]

  -r remote     : ip/host to serve shell/command (optionally prefixed with user@)
  -t ttyserver  : host to expose shell/command (localhost) (optionally prefixed with user@)
  -S sock       : unix socket file to listen/connect on remote (/tmp/.rbs.<uid>.<ttysrvname>.sock)
  -P passfile   : file containing password or '-' to enter interactively
  -T ttysrvname : ssh Host alias to connect to ttyserver (local)
  -R remotename : ssh Host alias to connect to remote (remote)
  -p port       : port to listen on remote (4444) instead of unix socket
  -b bind       : bind/connect address on remote(localhost)
  -C command    : shell command to execute on local and serve (bash -l)
  -c config     : config file to load (~/.rbs.conf)
  -a            : always serve (relaunch on disconnect)
  -s            : use ssh instead of script command to spawn shell/command when localhost

in your ~/.ssh/config add Include ~/.ssh/rbs (or ssh will be run with -F ~/.ssh/rbs)
'
  exit 0
}

rbs_pre() {
  logo=$(base64 -d <<'EOF'
G1szODs1OzE4NG0gG1szOW0bWzM4OzU7MjE0bSAbWzM5bRtbMzg7NTsyMTRtIBtbMzltG1szODs1
OzIwOG0gG1szOW0bWzM4OzU7MjA4bSAbWzM5bRtbMzg7NTsyMDNtIBtbMzltG1szODs1OzIwM20g
G1szOW0bWzM4OzU7MTk4bSAbWzM5bRtbMzg7NTsxOThtIBtbMzltG1szODs1OzE5OW1fG1szOW0b
WzM4OzU7MTk5bV8bWzM5bRtbMzg7NTsxNjRtIBtbMzltG1szODs1OzE2NG0gG1szOW0bWzM4OzU7
MTY0bSAbWzM5bRtbMzg7NTsxMjltIBtbMzltG1szODs1OzEyOW0gG1szOW0bWzM4OzU7OTNtIBtb
MzltG1szODs1OzkzbSAbWzM5bRtbMzg7NTs2M20gG1szOW0bWzM4OzU7NjNtG1szOW0KG1szODs1
OzIwOG0gG1szOW0bWzM4OzU7MjA4bSAbWzM5bRtbMzg7NTsyMDNtIBtbMzltG1szODs1OzIwM21f
G1szOW0bWzM4OzU7MTk4bV8bWzM5bRtbMzg7NTsxOThtXxtbMzltG1szODs1OzE5OW1fG1szOW0b
WzM4OzU7MTk5bV8bWzM5bRtbMzg7NTsxNjRtLxtbMzltG1szODs1OzE2NG0gG1szOW0bWzM4OzU7
MTY0bS8bWzM5bRtbMzg7NTsxMjltXxtbMzltG1szODs1OzEyOW0gG1szOW0bWzM4OzU7OTNtIBtb
MzltG1szODs1OzkzbV8bWzM5bRtbMzg7NTs2M21fG1szOW0bWzM4OzU7NjNtXxtbMzltG1szODs1
OzMzbV8bWzM5bRtbMzg7NTszM21fG1szOW0bWzM4OzU7MzltG1szOW0KG1szODs1OzIwM20gG1sz
OW0bWzM4OzU7MTk4bSAbWzM5bRtbMzg7NTsxOThtLxtbMzltG1szODs1OzE5OW0gG1szOW0bWzM4
OzU7MTk5bV8bWzM5bRtbMzg7NTsxNjRtXxtbMzltG1szODs1OzE2NG1fG1szOW0bWzM4OzU7MTY0
bS8bWzM5bRtbMzg7NTsxMjltIBtbMzltG1szODs1OzEyOW1fG1szOW0bWzM4OzU7OTNtXxtbMzlt
G1szODs1OzkzbSAbWzM5bRtbMzg7NTs2M21cG1szOW0bWzM4OzU7NjNtLxtbMzltG1szODs1OzMz
bSAbWzM5bRtbMzg7NTszM21fG1szOW0bWzM4OzU7MzltXxtbMzltG1szODs1OzM5bV8bWzM5bRtb
Mzg7NTs0NG0vG1szOW0bWzM4OzU7NDRtG1szOW0KG1szODs1OzE5OW0gG1szOW0bWzM4OzU7MTk5
bS8bWzM5bRtbMzg7NTsxNjRtIBtbMzltG1szODs1OzE2NG0vG1szOW0bWzM4OzU7MTY0bSAbWzM5
bRtbMzg7NTsxMjltIBtbMzltG1szODs1OzEyOW0vG1szOW0bWzM4OzU7OTNtIBtbMzltG1szODs1
OzkzbS8bWzM5bRtbMzg7NTs2M21fG1szOW0bWzM4OzU7NjNtLxtbMzltG1szODs1OzMzbSAbWzM5
bRtbMzg7NTszM20oG1szOW0bWzM4OzU7MzltXxtbMzltG1szODs1OzM5bV8bWzM5bRtbMzg7NTs0
NG0gG1szOW0bWzM4OzU7NDRtIBtbMzltG1szODs1OzQ5bSkbWzM5bRtbMzg7NTs0OW0gG1szOW0b
WzM4OzU7NDhtG1szOW0KG1szODs1OzE2NG0vG1szOW0bWzM4OzU7MTY0bV8bWzM5bRtbMzg7NTsx
MjltLxtbMzltG1szODs1OzEyOW0gG1szOW0bWzM4OzU7OTNtIBtbMzltG1szODs1OzkzbS8bWzM5
bRtbMzg7NTs2M21fG1szOW0bWzM4OzU7NjNtLhtbMzltG1szODs1OzMzbV8bWzM5bRtbMzg7NTsz
M21fG1szOW0bWzM4OzU7MzltXxtbMzltG1szODs1OzM5bS8bWzM5bRtbMzg7NTs0NG1fG1szOW0b
WzM4OzU7NDRtXxtbMzltG1szODs1OzQ5bV8bWzM5bRtbMzg7NTs0OW1fG1szOW0bWzM4OzU7NDht
LxtbMzltG1szODs1OzQ4bSAbWzM5bRtbMzg7NTs4M20gG1szOW0bWzM4OzU7ODNtG1szOW0KG1sz
ODs1OzEyOW0gG1szOW0bWzM4OzU7OTNtIBtbMzltG1szODs1OzkzbSAbWzM5bRtbMzg7NTs2M20g
G1szOW0bWzM4OzU7NjNtIBtbMzltG1szODs1OzMzbSAbWzM5bRtbMzg7NTszM20gG1szOW0bWzM4
OzU7MzltIBtbMzltG1szODs1OzM5bSAbWzM5bRtbMzg7NTs0NG0gG1szOW0bWzM4OzU7NDRtIBtb
MzltG1szODs1OzQ5bSAbWzM5bRtbMzg7NTs0OW0gG1szOW0bWzM4OzU7NDhtIBtbMzltG1szODs1
OzQ4bSAbWzM5bRtbMzg7NTs4M20gG1szOW0bWzM4OzU7ODNtIBtbMzltG1szODs1OzExOW0gG1sz
OW0bWzM4OzU7MTE4bSAbWzM5bRtbMzg7NTsxNTRtG1szOW0K
EOF
)
  printf '%s\n' "$logo"
  port=""
  password="$RB_PASS"
  ttyserver=localhost
  ttysrvname=local
  remotename=remote
  always=false
  use_ssh=false
  command="bash -l"
  ssh_proxy=false
  [ -f ~/.rbs.conf ] && . ~/.rbs.conf
  while getopts 'hsaxc:r:R:p:P:S:C:t:T:b:' opt;do
    case "$opt" in
      c) . "$OPTARG";;
      C) command="$OPTARG";;
      r) remote="$OPTARG";;
      t) ttyserver="$OPTARG";;
      p) port="$OPTARG";;
      P) passfile="$OPTARG";;
      T) ttysrvname="$OPTARG";;
      R) remotename="$OPTARG";;
      S) sock="$OPTARG";;
      a) always=true;;
      s) use_ssh=true;;
      b) bind="$OPTARG";;
      x) ssh_proxy=true;;
      h|\?) usage;;
    esac
  done
  [ "$bind" ] && port="${port:-4444}"
  bind="${bind:-localhost}"
  : ${UID:=$(id -u)}
  sockfile=${sock:-"/tmp/.rbs.$UID.$ttysrvname.sock"}
  sock=${sock:-"/tmp/.rbs.\$UID.$ttysrvname.sock"}
  [ ! "$remote" ] && [ ! -e "$sockfile" ] && port="${port:-4444}"
  [[ $remote = *@* ]] && user="User ${remote%@*}" || user=""
  remote=${remote##*@}
  ttyuser=""
  tuser="$USER"
  [[ $ttyserver = *@* ]] && tuser=${ttyserver%@*} && ttyuser="User $tuser"
  ttyserver=${ttyserver##*@}
  [ "$ttyserver" != localhost ] && use_ssh=true
  pre_cmd=": \${UID:=\$(id -u)};echo \"$tuser@$ttyserver[$ttysrvname]:$command -> \$USER@$remote[$remotename]:${port:-$sock}\" >&2;"
  [ "$port" ] && {
    connect_cmd="exec socat STDIO,raw,echo=0 TCP:$bind:$port"
    listen_cmd="socat - TCP-LISTEN:$port,bind=$bind,reuseaddr"
    proxy_cmd="bash -c '{ echo %h; cat; } |nc localhost $port'"
  } || {
    connect_cmd="exec socat STDIO,raw,echo=0 UNIX-CONNECT:$sockfile"
    listen_cmd="socat - UNIX-LISTEN:${sock##*/},mode=600"
    proxy_cmd="bash -c '{ echo %h; cat; } |nc -U $sockfile'"
    pre_cmd+="cd ${sock%/*};rm -f $sock;"
  }
  [ "$remote" ] || {
    printf '%s\n' "Connect: ${connect_cmd##* }"
    $connect_cmd
    exit
  }
  [ "$passfile" ] && {
    [ "$passfile" = - ] && { read -s -p "Password: " password;echo; } || password=$(cat "$passfile")
  }

  [ "$password" ] && {
    token=$(openssl rand -base64 32 | tr '+/' '-_' | tr -d '=')
    gpg64=$(gpg -c --batch --cipher-algo AES256 --passphrase-file <(printf %s $password) <<<"$token" |base64 -w0)
    tty_cmd=$(cat - <<EOF
read -s -p "Password: " p;base64 -d <<<$gpg64 | gpg -d --batch --passphrase-file <(printf %s "\$p") >/dev/null 2>&1 || exit 1
EOF
    )
  } || tty_cmd='read -s -n 1 -p "Press any key to continue..."'
  tty_cmd="$tty_cmd; echo; cd; type resize >/dev/null 2>&1 && . <(resize 2>/dev/null); rm -f ~/.ssh/.bashrc;RBS=true exec $command"
  $ssh_proxy && {
    command="proxy"
    pre_cmd+="base64 -d <<<$(base64 -w0 <<EOF
Host *
  ProxyCommand $proxy_cmd
EOF
) >~/.ssh/rbs_proxy;"
    tty_cmd=$'read h;echo "Connect to $h">&2;nc $h 22'
  }
  $use_ssh || echo "$tty_cmd" >~/.ssh/.bashrc
  cat - >~/.ssh/rbs <<EOF
Host $remotename
  Hostname $remote
  RequestTTY no
  RemoteCommand $pre_cmd pkill -U \$UID -f "^$listen_cmd"; sleep 1;exec $listen_cmd
  $user

Host $ttysrvname
  Hostname $ttyserver
  RequestTTY force
  RemoteCommand exec bash --rcfile <(printf %%s '${tty_cmd//%/%%}')
  $ttyuser

EOF
}
[ "$_rbs_post" ] || {
  rbs_pre "$@"
  export remotename ttysrvname always use_ssh ssh_proxy
  _rbs_post=1 exec bash <$0
}
grep -q "^[[:space:]]*Include ~/.ssh/rbs" ~/.ssh/config && ssh_conf='' || ssh_conf='-F rbs'
cd ~/.ssh
ssh_config="$(cat rbs)"
! $use_ssh && bashrc="$(cat .bashrc)" && rm .bashrc || bashrc=""
fifo="$(mktemp -u -t .XXXXXXXXXXX)"
trap "rm -f $fifo ~/.ssh/.bashrc;> ~/.ssh/rbs" EXIT

serve() {
  #  script -q -f -c "exec bash --rcfile .bashrc" /dev/null <$fifo |ssh $remotename $ssh_conf >$fifo
  #  ssh $ttysrvname $ssh_conf <$fifo | ssh $remotename $ssh_conf >$fifo
  # use coproc to kill $ttyserver shell/ssh on remote disconnect
  
  [ "$bashrc" ] && printf '%s' "$bashrc" >.bashrc
  (umask 0077;mkfifo $fifo) || exit 1
  $ssh_proxy && {
    $use_ssh && coproc PROD { exec ssh $ttysrvname $ssh_conf <$fifo; } \
             || coproc PROD { exec bash .bashrc <$fifo; } 
  } || {
    $use_ssh && coproc PROD { exec ssh $ttysrvname $ssh_conf <$fifo; } \
             || coproc PROD { exec script -qfc "exec bash --rcfile .bashrc" /dev/null <$fifo; }
  }
  printf '%s' "$ssh_config" >rbs
  (
    sleep 0.5
    rm -f $fifo
    >rbs
  ) &
  ssh $remotename $ssh_conf >$fifo <&"${PROD[0]}"
  kill "$PROD_PID" 2>/dev/null
  wait
}

serve_always() {
  while true;do
    serve
    sleep 2 & wait
  done
}

$always && {
  trap "trap - INT TERM;kill 0" INT TERM
  serve_always
  exit
}

serve 
