#!/bin/bash
# reverse shell/command/proxy over ssh stdio
# from a host, serves an interactive shell/command on a remote host using simple ssh
# connnect to it from remote host
# example:
#   serve a shell on host to remote: rbs -r <remote> 
#   connect to host from remote: rbs
#
# rbs uses the ssh connection issued from host stdin/stdout to act as network transport, 
# so it works even if ssh is the only allowed traffic to the remote host, and no traffic allowed from remote host to host. 
# It can also be used as a reverse ssh proxy to access other hosts from the remote host through host.
#
# Author: joknarf

usage() {
  printf '%s' "usage: 
  server: rbs -r [<user>@]<remote>[:<port>|:<sock>] [-P <passfile|->] [-t [<user>@]<ttyserver>] [-T <ttysrvname>] [-R <remotename>] [-b <bind>] [-c config] [-C <command>] [-a] [-s]
  client: rbs [<remote>][:<port>|:<sock>] -T <ttysrvname>]

  -r remote     : ip/host to serve shell/command
  user@         : optional ssh user for remote
  :sock         : unix socket file to listen/connect on remote (/tmp/.rbs.<uid>.<ttysrvname>.sock)
  :port         : port to listen on remote (4444) instead of unix socket
  -t ttyserver  : host to expose shell/command (localhost) (optionally prefixed with user@)
  -P passfile   : file containing password or '-' to enter interactively
  -T ttysrvname : ssh Host alias to connect to ttyserver (local)
  -R remotename : ssh Host alias to connect to remote (remote)
  -b bind       : bind/connect address on remote (localhost)
  -C command    : shell command to execute on local and serve (bash -l)
  -c config     : config file to load (~/.rbs.conf)
  -x            : reverse ssh proxy (ssh -F ~/.ssh/rbs_proxy on remote to use proxy)
  -a            : always serve (relaunch on disconnect)
  -s            : use ssh instead of script command to spawn shell/command when localhost
  -e            : use expect instead of script to spawn shell/command (macOS script won't work)

in your ~/.ssh/config add Include ~/.ssh/rbs (or ssh will be run with -F ~/.ssh/rbs)
"
  exit 0
}

rbs_pre() {
  logo=$(base64 -d <<'EOF'
G1szODs1OzE4NG0gG1szOW0bWzM4OzU7MjE0bSAbWzM5bRtbMzg7NTsyMTRtIBtbMzltG1szODs1
OzIwOG0gG1szOW0bWzM4OzU7MjA4bSAbWzM5bRtbMzg7NTsyMDNtIBtbMzltG1szODs1OzIwM20g
G1szOW0bWzM4OzU7MTk4bSAbWzM5bRtbMzg7NTsxOThtIBtbMzltG1szODs1OzE5OW1fG1szOW0b
WzM4OzU7MTk5bV8bWzM5bRtbMzg7NTsxNjRtIBtbMzltG1szODs1OzE2NG0gG1szOW0bWzM4OzU7
MTY0bSAbWzM5bRtbMzg7NTsxMjltIBtbMzltG1szODs1OzEyOW0gG1szOW0bWzM4OzU7OTNtIBtb
MzltG1szODs1OzkzbSAbWzM5bRtbMzg7NTs2M20gG1szOW0bWzM4OzU7NjNtG1szOW0KG1szODs1
OzIwOG0gG1szOW0bWzM4OzU7MjA4bSAbWzM5bRtbMzg7NTsyMDNtIBtbMzltG1szODs1OzIwM21f
G1szOW0bWzM4OzU7MTk4bV8bWzM5bRtbMzg7NTsxOThtXxtbMzltG1szODs1OzE5OW1fG1szOW0b
WzM4OzU7MTk5bV8bWzM5bRtbMzg7NTsxNjRtLxtbMzltG1szODs1OzE2NG0gG1szOW0bWzM4OzU7
MTY0bS8bWzM5bRtbMzg7NTsxMjltXxtbMzltG1szODs1OzEyOW0gG1szOW0bWzM4OzU7OTNtIBtb
MzltG1szODs1OzkzbV8bWzM5bRtbMzg7NTs2M21fG1szOW0bWzM4OzU7NjNtXxtbMzltG1szODs1
OzMzbV8bWzM5bRtbMzg7NTszM21fG1szOW0bWzM4OzU7MzltG1szOW0KG1szODs1OzIwM20gG1sz
OW0bWzM4OzU7MTk4bSAbWzM5bRtbMzg7NTsxOThtLxtbMzltG1szODs1OzE5OW0gG1szOW0bWzM4
OzU7MTk5bV8bWzM5bRtbMzg7NTsxNjRtXxtbMzltG1szODs1OzE2NG1fG1szOW0bWzM4OzU7MTY0
bS8bWzM5bRtbMzg7NTsxMjltIBtbMzltG1szODs1OzEyOW1fG1szOW0bWzM4OzU7OTNtXxtbMzlt
G1szODs1OzkzbSAbWzM5bRtbMzg7NTs2M21cG1szOW0bWzM4OzU7NjNtLxtbMzltG1szODs1OzMz
bSAbWzM5bRtbMzg7NTszM21fG1szOW0bWzM4OzU7MzltXxtbMzltG1szODs1OzM5bV8bWzM5bRtb
Mzg7NTs0NG0vG1szOW0bWzM4OzU7NDRtG1szOW0KG1szODs1OzE5OW0gG1szOW0bWzM4OzU7MTk5
bS8bWzM5bRtbMzg7NTsxNjRtIBtbMzltG1szODs1OzE2NG0vG1szOW0bWzM4OzU7MTY0bSAbWzM5
bRtbMzg7NTsxMjltIBtbMzltG1szODs1OzEyOW0vG1szOW0bWzM4OzU7OTNtIBtbMzltG1szODs1
OzkzbS8bWzM5bRtbMzg7NTs2M21fG1szOW0bWzM4OzU7NjNtLxtbMzltG1szODs1OzMzbSAbWzM5
bRtbMzg7NTszM20oG1szOW0bWzM4OzU7MzltXxtbMzltG1szODs1OzM5bV8bWzM5bRtbMzg7NTs0
NG0gG1szOW0bWzM4OzU7NDRtIBtbMzltG1szODs1OzQ5bSkbWzM5bRtbMzg7NTs0OW0gG1szOW0b
WzM4OzU7NDhtG1szOW0KG1szODs1OzE2NG0vG1szOW0bWzM4OzU7MTY0bV8bWzM5bRtbMzg7NTsx
MjltLxtbMzltG1szODs1OzEyOW0gG1szOW0bWzM4OzU7OTNtIBtbMzltG1szODs1OzkzbS8bWzM5
bRtbMzg7NTs2M21fG1szOW0bWzM4OzU7NjNtLhtbMzltG1szODs1OzMzbV8bWzM5bRtbMzg7NTsz
M21fG1szOW0bWzM4OzU7MzltXxtbMzltG1szODs1OzM5bS8bWzM5bRtbMzg7NTs0NG1fG1szOW0b
WzM4OzU7NDRtXxtbMzltG1szODs1OzQ5bV8bWzM5bRtbMzg7NTs0OW1fG1szOW0bWzM4OzU7NDht
LxtbMzltG1szODs1OzQ4bSAbWzM5bRtbMzg7NTs4M20gG1szOW0bWzM4OzU7ODNtG1szOW0KG1sz
ODs1OzEyOW0gG1szOW0bWzM4OzU7OTNtIBtbMzltG1szODs1OzkzbSAbWzM5bRtbMzg7NTs2M20g
G1szOW0bWzM4OzU7NjNtIBtbMzltG1szODs1OzMzbSAbWzM5bRtbMzg7NTszM20gG1szOW0bWzM4
OzU7MzltIBtbMzltG1szODs1OzM5bSAbWzM5bRtbMzg7NTs0NG0gG1szOW0bWzM4OzU7NDRtIBtb
MzltG1szODs1OzQ5bSAbWzM5bRtbMzg7NTs0OW0gG1szOW0bWzM4OzU7NDhtIBtbMzltG1szODs1
OzQ4bSAbWzM5bRtbMzg7NTs4M20gG1szOW0bWzM4OzU7ODNtIBtbMzltG1szODs1OzExOW0gG1sz
OW0bWzM4OzU7MTE4bSAbWzM5bRtbMzg7NTsxNTRtG1szOW0K
EOF
)
  umask 077
  printf '%s\n' "$logo"
  port=""
  password="$RB_PASS"
  ttyserver=localhost
  ttysrvname=local
  remotename=remote
  always=false
  use_ssh=false
  command="bash -l"
  ssh_proxy=false
  use_expect=false
  [ -f ~/.rbs.conf ] && . ~/.rbs.conf
  while getopts 'hseaxc:r:R:p:P:S:C:t:T:b:' opt;do
    case "$opt" in
      c) . "$OPTARG";;
      C) command="$OPTARG";;
      r) remote_host="$OPTARG";;
      t) ttyserver="$OPTARG";;
      P) passfile="$OPTARG";;
      T) ttysrvname="$OPTARG";;
      R) remotename="$OPTARG";;
      a) always=true;;
      s) use_ssh=true;;
      e) use_expect=true;;
      b) bind="$OPTARG";;
      x) ssh_proxy=true;;
      h|\?) usage;;
    esac
  done
  shift $((OPTIND-1))
  [ "$1" ] && remote="$1" || remote=localhost
  [ "$remote_host" ] && remote="$remote_host"
  [[ $remote = *:* ]] && {
    remote_port="${remote##*:}"
    [[ $remote_port =~ ^[0-9]+$ ]] && port=$remote_port || sock=$remote_port
  }
  remote=${remote%%:*}
  [ "$remote" ] || remote=localhost
  
  [[ $remote = *@* ]] && user="User ${remote%@*}" || user=""
  remote=${remote##*@}
  [ "$bind" ] && port="${port:-4444}"
  bind="${bind:-localhost}"
  : ${UID:=$(id -u)}
  sockfile=${sock:-"/tmp/.rbs.$UID.$ttysrvname.sock"}
  sock=${sock:-"/tmp/.rbs.\$UID.$ttysrvname.sock"}
  [ ! "$remote_host" ] && [ ! -e "$sockfile" ] && port="${port:-4444}"
  ttyuser=""
  tuser="$USER"
  [[ $ttyserver = *@* ]] && tuser=${ttyserver%@*} && ttyuser="User $tuser"
  ttyserver=${ttyserver##*@}
  [ "$ttyserver" != localhost ] && use_ssh=true
  pre_cmd=": \${UID:=\$(id -u)};echo \"$tuser@$ttyserver[$ttysrvname]:$command -> \$USER@$remote[$remotename]:${port:-$sock}\" >&2;"
  [ "$port" ] && {
    connect_cmd="exec socat STDIO,raw,echo=0 TCP:$remote:$port"
    listen_cmd="socat -d0 - TCP-LISTEN:$port,bind=$bind,reuseaddr"
    proxy_cmd="bash -c '{ echo %h; cat; } |nc localhost $port'"
  } || {
    connect_cmd="exec socat STDIO,raw,echo=0 UNIX-CONNECT:$sockfile"
    listen_cmd="socat -d0 - UNIX-LISTEN:${sock##*/},mode=600"
    proxy_cmd="bash -c '{ echo %h; cat; } |nc -U $sockfile'"
    pre_cmd+="cd ${sock%/*};rm -f $sock;"
  }
  [ "$remote_host" ] || {
    printf '%s\n' "Connect: ${connect_cmd##* }"
    # early cleanup socket
    [ "$sockfile" ] && ( (sleep 0.5;[ -S "$sockfile" ] && rm -f "$sockfile") & ) &
    wait
    $connect_cmd
  }
  [ "$passfile" ] && {
    [ "$passfile" = - ] && { read -s -p "Password: " password;echo; } || password=$(cat "$passfile")
  }

  [ "$password" ] && {
    token=$(openssl rand -base64 32)
    gpg64=$(gpg -c --batch --cipher-algo AES256 --passphrase-file <(printf %s $password) <<<"$token" |base64 -w0)
    tty_cmd=$(cat - <<EOF
rm -f ~/.ssh/.bashrc ~/.ssh/.exp
read -s -p "Password: " p;base64 -d <<<$gpg64 | gpg -d --batch --passphrase-file <(printf %s "\$p") >/dev/null 2>&1 || exit 1
EOF
    )
  } || tty_cmd='rm -f ~/.ssh/.bashrc ~/.ssh/.exp;read -s -n 1 -p "Press any key to continue..."'
  tty_cmd+="$(cat - <<'EOF'

type -p resize >/dev/null 2>&1 || resize() {
  typeset oldstty rows cols
  oldstty=$(stty -g)
  stty raw -echo min 0 time 5
  printf '\033[18t' > /dev/tty
  IFS=';' read -r -d t _ rows cols < /dev/tty
  stty "$oldstty"
  if [[ $rows =~ ^[0-9]+$ && $cols =~ ^[0-9]+$ ]]; then
    printf 'stty rows "%s" cols "%s"' "$rows" "$cols"
  fi
}
echo
. <(resize 2>/dev/null)
cd
RBS=true 
EOF
  )"
  # warn: += appends at end of line, not new line
  tty_cmd+=" exec $command"

  $ssh_proxy && {
    command="proxy"
    pre_cmd+="base64 -d <<<$(base64 -w0 <<EOF
Host *
  ProxyCommand $proxy_cmd
EOF
) >~/.ssh/rbs_proxy;"
    tty_cmd=$'read h;echo "Connect to $h">&2;nc $h 22'
  }
  $use_ssh || echo "$tty_cmd" >~/.ssh/.bashrc
  cat - >~/.ssh/rbs <<EOF
Host $remotename
  Hostname $remote
  RequestTTY no
  RemoteCommand bash <(base64 -d <<<$(base64 -w0 <<<"$pre_cmd pkill -U \$UID -f \"^$listen_cmd\";exec $listen_cmd"))
  $user

Host $remotename.cleanup
  Hostname $remote
  RequestTTY no
  RemoteCommand bash <(base64 -d <<<$(base64 -w0 <<<"pkill -U \$UID -f \"^$listen_cmd\""))
  $user

Host $ttysrvname
  Hostname $ttyserver
  RequestTTY force
  RemoteCommand bash --rcfile <(base64 -d <<<$(base64 -w0 <<<"$tty_cmd"))
  $ttyuser

EOF
}
[ "$_rbs_post" ] || {
  rbs_pre "$@"
  export remotename ttysrvname always use_ssh ssh_proxy use_expect
  _rbs_post=1 exec bash <$0
}
unset _rbs_post
grep -q "^[[:space:]]*Include ~/.ssh/rbs" ~/.ssh/config 2>/dev/null && ssh_conf='' || ssh_conf='-F rbs'
cd ~/.ssh
ssh_config="$(cat rbs)"
! $use_ssh && bashrc="$(cat .bashrc)" && rm .bashrc || bashrc=""
fifo="$(mktemp -u)"
trap "rm -f $fifo ~/.ssh/.bashrc;> ~/.ssh/rbs" EXIT

localcmd() {
  $use_expect && {
    cat >.exp <<<'log_user 0;set timeout -1;spawn bash --rcfile .bashrc;interact'
    exec expect -f .exp
  } || exec script -qfc 'bash --rcfile .bashrc' /dev/null
}

serve() {
  #  script -qfc "exec bash --rcfile .bashrc" /dev/null <$fifo |ssh $remotename $ssh_conf >$fifo
  #  expect -f <<<'set timeout -1;spawn bash --rcfile .bashrc;interact'
  #  ssh $ttysrvname $ssh_conf <$fifo | ssh $remotename $ssh_conf >$fifo
  # use coproc to kill $ttyserver shell/ssh on remote disconnect
  
  [ "$bashrc" ] && printf '%s' "$bashrc" >.bashrc
  rm -f $fifo
  mkfifo $fifo || exit 1
  $ssh_proxy && {
    $use_ssh && coproc PROD { exec ssh $ttysrvname $ssh_conf <$fifo; } \
             || coproc PROD { exec bash .bashrc <$fifo; } 
  } || {
    $use_ssh && coproc PROD { exec ssh $ttysrvname $ssh_conf <$fifo; } \
             || coproc PROD { localcmd <$fifo; }
  }
  printf '%s' "$ssh_config" >rbs
  (
    sleep 0.5
    rm -f $fifo
    >rbs
  ) &
  ssh $remotename $ssh_conf >$fifo <&"${PROD[0]}"
  kill "$PROD_PID" 2>/dev/null
  wait
}

serve_always() {
  while true;do
    serve
    sleep 2 & wait
  done
}

cleanup() {
  trap - INT TERM
  echo "Cleaning up..." >&2
  echo "$ssh_config" >~/.ssh/rbs
  ssh $remotename.cleanup $ssh_conf
  rm -f $fifo ~/.ssh/.bashrc
  > ~/.ssh/rbs
  kill 0
  exit
}

trap cleanup INT TERM

$always && {
  serve_always
  exit
}


serve 
